title: Sarifah Sapuan # your name (or website title) here
logo: "/images/photo6.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Analyst
  <br><br>
  I am a seasoned IT professional with 3 decades of experience in customer support, systems implementation, applications support and IT support roles.
  <br><br>
  I recently completed my Associate Data Analyst training : 
  <br><br>
    Advanced MS Excel, MS SQL, Power BI,    
    Python3 Programming, ETL operations, Machine Learning models and Advanced Analytics,  
    Statistics and Maths for Data Science and Business Analysis
  
  <br><br>
  <a href="https://www.linkedin.com/in/sarifah-sapuan-7157045/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
