title: Sarifah Sapuan # your name (or website title) here
logo: "/images/photo6.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Analyst
  <br><br>
  I am a seasoned IT professional with 3 decades of experience in customer support, systems implementation, applications support and IT support roles.
  <br><br>
  During a recent forced work break, I had the opportunity discover new skills and brush up on some existing skills.
  <br><br>
  Here I am now an aspiring data analyst having completed my trainings : 
    Advanced MS Excel  
    MS SQL incl DB Admin, ETL operations, Data Analysis  
    PowerBI in Data Analysis and Visualization and presentation  
    Python incl Python3 Programming, Automate Repetitive Task, ETL operations, Machine Learning models and Advanced Analytics  
    Statistics for Data Science and Business Analysis, Calculus and Optimization, Matrices and Linear Algebra
  
  <br><br>
  <a href="https://www.linkedin.com/in/sarifah-sapuan-7157045/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
